### ISSUE TITLE
feature request | show what apps are running

### ISSUE THREAD

**Issue by Pan00Pernicek** [farmerbb/Taskbar#111]
like chrome os 
https://1drv.ms/u/s!ApRQygiWuy_t0nqspkz_tEfW-Knd
I am not sure if its possible to do it on android , but it would be great feature.

**Comment by konnaris** [comment]
+1 for this feature and/or provide an overlay whilst using alt-tab (only Sentio seems to have this)

**Comment by farmerbb** [comment]
This feature is already implemented, but it requires Taskbar to be installed on your device's system partition as Android has restricted the relevant APIs so that they can only be used by system apps.  (This requires a rooted device)

Once you've done this, go to "Recent apps" in settings and change "Recent apps to display" to "Running apps only".

Note that Taskbar on Bliss OS and Android-x86 has this enabled by default since Taskbar is installed as a system app on both of those Android distributions.

**Comment by konnaris** [comment]
Thanks, I've tried your instructions on two different rooted ROM's and was able to set "Running apps only", however, no apps show up on the Taskbar.  Perhaps I'm missing something else?

**Comment by farmerbb** [comment]
Sorry for the late reply.  Taskbar needs to be moved into the `/system/priv-app` directory in order for the "Running apps only" option to work.  Can you double-check that Taskbar is installed in the right directory?

**Comment by konnaris** [comment]
Many thanks, I was moving it to `/system/app` and not `/system/priv-app` its working now
