### ISSUE TITLE
Widgets freeze after some time.

### ISSUE THREAD

**Issue by CrimsonFork** [farmerbb/Taskbar#24]
If it helps, [Silverfish](https://github.com/stanipintjuk/Silverfish) asks for a permission on my phone (Stock 5.1.1), for creating Widgets and accessing their data.

**Comment by farmerbb** [comment]
It's not a permissions issue (I'm using an older method to bind widgets that does not require android.permission.BIND_APPWIDGET), otherwise widgets wouldn't be working at all.

To be honest it's an issue that I've seen with apps in general that host widgets.  I'll keep my eye out for ways to improve how widgets are handled, but I'm not sure how to fix this at this time.

Do you have any examples of widgets that freeze?

**Comment by OffifialMITX** [comment]
Ok, but the thing is that Silverfish for example creates the widget, it works, and only after a while asks for the permission. Taskbar acts just like this but instead of asking for the permission tge widgets stop working.

Besides, it's not actually freeze, the widgets seem to not be connected to their app. You can press buttons, you have visual feedback, but nothing happens.

It happens to every widget after like a day (no restart) no matter if Android's internal apps (calendar / power managment) or any other one (e.g. [vlc (F-Droid version)](https://code.videolan.org/videolan/vlc-android) or [Red Moon](https://github.com/raatmarien/red-moon)).

**Comment by farmerbb** [comment]
Apps only need to ask for permission to bind widgets if they did not go through the system widget picker (which is what Taskbar does).  Are you sure that the apps providing the widgets aren't just being killed due to memory constraints?

**Comment by OffifialMITX** [comment]
Maybe, but I actualy never had problems with it - I have always at least 25% free.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.
